### ISSUE TITLE
Logo size

### ISSUE THREAD

**Issue by Diya92** [Diya92/Empays#1]
logo size should be r
![about us](https://user-images.githubusercontent.com/41475722/55156392-cb004600-517f-11e9-9546-f17cdfae0833.PNG)
estricted for **30-40px**

**Comment by Lavanya447** [comment]
fixed

**Comment by Diya92** [comment]
getting again in firefox browser
![banner](https://user-images.githubusercontent.com/41475722/55156607-67c2e380-5180-11e9-8f6c-9b9ebe25c716.PNG)
